language: node_js
node_js:
- 8
branches:
  only:
  - master
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.1
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn
before_script:
- yarn global add codecov
script:
- yarn run build
- yarn run test-cover
- codecov
cache:
  yarn: true
  directories:
    - "node_modules"
